spring:
  application:
    name: user-service
  config:
    import: "classpath:env.properties"
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/userdb #host.docker.internal
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: email,profile
            redirect-uri: http://localhost:9191/login/oauth2/code/google
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: profile
            redirect-uri: http://localhost:9191/login/oauth2/code/github
server:
  port: 9191